name: Helm Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm Chart
        run: |
          helm lint charts/mein-chart
